sonar.projectKey=DeepCheck
sonar.projectName=DeepCheck

sonar.host.url=http://localhost:9000

sonar.token=sqp_54e2f08bbc2b12904efea472e21ff8384d9803e9

sonar.sources=scanned_code.py

sonar.python.version=3

//pour eviter de scan notre code de .venv etc
sonar.exclusions=**/.venv/**,**/migrations/**,**/__pycache__/**,**/static/**,**/*.min.js
