# Generated by Django 6.0.4 on 2026-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_scanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='filename',
            field=models.CharField(default='unknown.py', max_length=255),
        ),
    ]
